name: Build and Publish Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # wymagane do pushowania do ghcr.io

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t sjuprojekt .

    - name: Run test script inside container
      run: |
        docker run --rm sjuprojekt python /home/vscode/workspace/test.py

    - name: Tag image for GHCR
      run: |
        docker tag sjuprojekt ghcr.io/${{ github.repository }}:latest
        docker tag sjuprojekt ghcr.io/${{ github.repository }}:${{ github.ref_name }}

    - name: Push image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
